### ISSUE TITLE
SyntaxError in django_heroku 

### ISSUE THREAD

**Issue by Alababdiy** [heroku/django-heroku#8]
## on i try run server
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dell/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/dell/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/dell/.local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/dell/.local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/dell/.local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/dell/Workshop/ArNews/python-getting-started/gettingstarted/settings.py", line 14, in <module>
    import django_heroku
  File "/usr/local/lib/python2.7/dist-packages/django_heroku/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/local/lib/python2.7/dist-packages/django_heroku/core.py", line 45
    def settings(config, *, db_colors=False, databases=True, test_runner=True, staticfiles=True, allowed_hosts=True, logging=True, secret_key=True):
                          ^
SyntaxError: invalid syntax

_i use python ver :  2.7.14_

**Comment by edmorley** [comment]
Hi!

From the project README:
> Django 2.0 is targeted, but older versions of Django should be compatible. Only Python 3 is supported.

**Comment by Alababdiy** [comment]
OKAY ! Thx.

**Comment by tlhcelik** [comment]
pip3 install -r reqs.txt 
it's work 👍

**Comment by OkamiMane** [comment]
> pip3 install -r reqs.txt
> it's work

I had to use pip3 install -r requirements.txt instead. Use whatever the file name in your directory is.
